---
abstract: 'Serve data in a Weighted RoundRobin manner.'
author:
  - 'xaicron <xaicron {at} cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.96
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-WeightedRoundRobin
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Data::WeightedRoundRobin:
    file: lib/Data/WeightedRoundRobin.pm
    version: 0.06
requires:
  Scope::Guard: 0
resources:
  bugtracker: https://github.com/xaicron/p5-Data-WeightedRoundRobin/issues
  homepage: https://github.com/xaicron/p5-Data-WeightedRoundRobin
  repository: git://github.com/xaicron/p5-Data-WeightedRoundRobin.git
version: 0.06
x_contributors:
  - 'xaicron <xaicron@gmail.com>'
